from enum import Enum


class BooleanType(Enum):
    FALSE = 0
    TRUE = 1

class HessianType(Enum):
	ZERO = 0			
	IDENTITY =1
	POSDEF =2
	POSDEF_NULLSPACE = 3
	SEMIDEF = 4
	INDEF = 5
	UNKNOWN = 6

class ReturnValue(Enum):
    TERMINAL_LIST_ELEMENT = -1			    		# Terminal list element, internal usage only! 	
    SUCCESSFUL_RETURN = 0							# Successful return. 
    DIV_BY_ZERO = 1	   					        	# Division by zero. 
    INDEX_OUT_OF_BOUNDS = 2					     	# Index out of bounds. 
    INVALID_ARGUMENTS =3							# At least one of the arguments is invalid. 
    ERROR_UNDEFINED = 4				                # Error number undefined. 
    WARNING_UNDEFINED = 5							    # Warning number undefined. 
    INFO_UNDEFINED = 6					            # Info number undefined. 
    EWI_UNDEFINED = 7								# Error/warning/info number undefined. 
    AVAILABLE_WITH_LINUX_ONLY = 8					# This function is available under Linux only. 
    UNKNOWN_BUG = 9								    # The error occurred is not yet known. 
    PRINTLEVEL_CHANGED = 10							# Print level changed. (10) 
    NOT_YET_IMPLEMENTED = 11						# Requested function is not yet implemented in this version of qpOASES. 
    INDEXLIST_MUST_BE_REORDERD = 12				    # Index list has to be reordered. 
    INDEXLIST_EXCEEDS_MAX_LENGTH = 13				# Index list exceeds its maximal physical length. 
    INDEXLIST_CORRUPTED = 14						# Index list corrupted. 
    INDEXLIST_OUTOFBOUNDS= 15						# Physical index is out of bounds. 
    INDEXLIST_ADD_FAILED = 16						# Adding indices from another index set failed. 
    INDEXLIST_INTERSECT_FAILED = 17					# Intersection with another index set failed. 
    INDEX_ALREADY_OF_DESIRED_STATUS = 18			# Index is already of desired status. (18) 
    ADDINDEX_FAILED = 19							# Adding index to index set failed. 
    REMOVEINDEX_FAILED = 20							# Removing index from index set failed. (20) 
    SWAPINDEX_FAILED = 21							# Cannot swap between different indexsets. 
    NOTHING_TO_DO= 22								# Nothing to do. 
    SETUP_BOUND_FAILED = 23							# Setting up bound index failed. 
    SETUP_CONSTRAINT_FAILED = 24					# Setting up constraint index failed. 
    MOVING_BOUND_FAILED= 25						    # Moving bound between index sets failed. 
    MOVING_CONSTRAINT_FAILED = 26					# Moving constraint between index sets failed. 
    SHIFTING_FAILED = 27							# Shifting of bounds/constraints failed. 
    ROTATING_FAILED = 28							# Rotating of bounds/constraints failed. 
    QPOBJECT_NOT_SETUP = 29							# The QP object has not been setup correctly, use another constructor. 
    QP_ALREADY_INITIALISED = 30						# QProblem has already been initialised. (30) 
    NO_INIT_WITH_STANDARD_SOLVER = 31				# Initialisation via extern QP solver is not yet implemented. 
    RESET_FAILED = 32							    # Reset failed. 
    INIT_FAILED = 33								# Initialisation failed. 
    INIT_FAILED_TQ= 34								# Initialisation failed due to TQ factorisation. 
    INIT_FAILED_CHOLESKY = 35						# Initialisation failed due to Cholesky decomposition. 
    INIT_FAILED_HOTSTART = 36						# Initialisation failed! QP could not be solved! 
    INIT_FAILED_INFEASIBILITY = 37					# Initial QP could not be solved due to infeasibility! 
    INIT_FAILED_UNBOUNDEDNESS = 38					# Initial QP could not be solved due to unboundedness! 
    INIT_FAILED_REGULARISATION = 39					# Initialisation failed as Hessian matrix could not be regularised. 
    INIT_SUCCESSFUL = 40						    # Initialisation done. (40) 
    OBTAINING_WORKINGSET_FAILED = 41				# Failed to obtain working set for auxiliary QP. 
    SETUP_WORKINGSET_FAILED = 42					# Failed to setup working set for auxiliary QP. 
    SETUP_AUXILIARYQP_FAILED= 43					# Failed to setup auxiliary QP for initialised homotopy. 
    NO_CHOLESKY_WITH_INITIAL_GUESS = 44				# Externally computed Cholesky factor cannot be combined with an initial guess. 
    NO_EXTERN_SOLVER = 45							# No extern QP solver available. 
    QP_UNBOUNDED = 46								# QP is unbounded. 
    QP_INFEASIBLE = 47								# QP is infeasible. 
    QP_NOT_SOLVED = 48								# Problems occurred while solving QP with standard solver. 
    QP_SOLVED = 49									# QP successfully solved. 
    UNABLE_TO_SOLVE_QP = 50							# Problems occurred while solving QP. (50) 
    INITIALISATION_STARTED = 51					    # Starting problem initialisation... 
    HOTSTART_FAILED = 52							# Unable to perform homotopy due to internal error. 
    HOTSTART_FAILED_TO_INIT = 53					# Unable to initialise problem. 
    HOTSTART_FAILED_AS_QP_NOT_INITIALISED = 54		# Unable to perform homotopy as previous QP is not solved. 
    ITERATION_STARTED = 55							# Iteration...
    SHIFT_DETERMINATION_FAILED = 56					# Determination of shift of the QP data failed. 
    STEPDIRECTION_DETERMINATION_FAILED = 57			# Determination of step direction failed. 
    STEPLENGTH_DETERMINATION_FAILED = 58			# Determination of step direction failed. 
    OPTIMAL_SOLUTION_FOUND = 59				    	# Optimal solution of neighbouring QP found. 
    HOMOTOPY_STEP_FAILED = 60						# Unable to perform homotopy step. (60) 
    HOTSTART_STOPPED_INFEASIBILITY = 61				# Premature homotopy termination because QP is infeasible. 
    HOTSTART_STOPPED_UNBOUNDEDNESS = 62	            # Premature homotopy termination because QP is unbounded. 
    WORKINGSET_UPDATE_FAILED = 63					# Unable to update working sets according to initial guesses. 
    MAX_NWSR_REACHED = 64							# Maximum number of working set recalculations performed. 
    CONSTRAINTS_NOT_SPECIFIED = 65					# Problem does comprise constraints! You also have to specify new constraints' bounds. 
    INVALID_FACTORISATION_FLAG = 66					# Invalid factorisation flag. 
    UNABLE_TO_SAVE_QPDATA = 67						# Unable to save QP data. 
    STEPDIRECTION_FAILED_TQ = 68			     	# Abnormal termination due to TQ factorisation. 
    STEPDIRECTION_FAILED_CHOLESKY = 69				# Abnormal termination due to Cholesky factorisation. 
    CYCLING_DETECTED = 70					    	# Cycling detected. (70) 
    CYCLING_NOT_RESOLVED = 71						# Cycling cannot be resolved, QP probably infeasible. 
    CYCLING_RESOLVED = 72				        	# Cycling probably resolved. 
    STEPSIZE = 73							        # For displaying performed stepsize. 
    STEPSIZE_NONPOSITIVE = 74						# For displaying non-positive stepsize. 
    SETUPSUBJECTTOTYPE_FAILED = 75					# Setup of SubjectToTypes failed. 
    ADDCONSTRAINT_FAILED = 76				     	# Addition of constraint to working set failed. 
    ADDCONSTRAINT_FAILED_INFEASIBILITY = 77			# Addition of constraint to working set failed (due to QP infeasibility). 
    ADDBOUND_FAILED = 78							# Addition of bound to working set failed. 
    ADDBOUND_FAILED_INFEASIBILITY = 79				# Addition of bound to working set failed (due to QP infeasibility). 
    REMOVECONSTRAINT_FAILED = 80					# Removal of constraint from working set failed. (80) 
    REMOVEBOUND_FAILED = 81					     	# Removal of bound from working set failed. 
    REMOVE_FROM_ACTIVESET = 82						# Removing from active set... 
    ADD_TO_ACTIVESET = 83					    	# Adding to active set... 
    REMOVE_FROM_ACTIVESET_FAILED = 84				# Removing from active set failed. 
    ADD_TO_ACTIVESET_FAILED = 85					# Adding to active set failed. 
    CONSTRAINT_ALREADY_ACTIVE = 86					# Constraint is already active. 
    ALL_CONSTRAINTS_ACTIVE = 87					    # All constraints are active, no further constraint can be added. 
    LINEARLY_DEPENDENT = 88							# New bound/constraint is linearly dependent. 
    LINEARLY_INDEPENDENT= 89						# New bound/constraint is linearly independent. 
    LI_RESOLVED = 90						        # Linear independence of active constraint matrix successfully resolved. (90) 
    ENSURELI_FAILED = 91						    # Failed to ensure linear independence of active constraint matrix. 
    ENSURELI_FAILED_TQ = 92						    # Abnormal termination due to TQ factorisation. 
    ENSURELI_FAILED_NOINDEX = 93					# QP is infeasible. 
    ENSURELI_FAILED_CYCLING = 94					# QP is infeasible. 
    BOUND_ALREADY_ACTIVE = 95						# Bound is already active. 
    ALL_BOUNDS_ACTIVE = 96							# All bounds are active, no further bound can be added. 
    CONSTRAINT_NOT_ACTIVE = 97						# Constraint is not active. 
    BOUND_NOT_ACTIVE = 98						    # Bound is not active. 
    HESSIAN_NOT_SPD = 99							# Projected Hessian matrix not positive definite. 
    HESSIAN_INDEFINITE = 100						# Hessian matrix is indefinite. (100) 
    MATRIX_SHIFT_FAILED = 101						# Unable to update matrices or to transform vectors. 
    MATRIX_FACTORISATION_FAILED = 102				# Unable to calculate new matrix factorisations. 
    PRINT_ITERATION_FAILED = 103					# Unable to print information on current iteration. 
    NO_GLOBAL_MESSAGE_OUTPUTFILE = 104				# No global message output file initialised. 
    DISABLECONSTRAINTS_FAILED = 105				    # Unable to disbable constraints. 
    ENABLECONSTRAINTS_FAILED = 106				    # Unable to enbable constraints. 
    ALREADY_ENABLED = 107					        # Bound or constraint is already enabled. 
    ALREADY_DISABLED = 108					     	# Bound or constraint is already disabled. 
    NO_HESSIAN_SPECIFIED = 109						# No Hessian matrix has been specified. 
    USING_REGULARISATION = 110						# Using regularisation as Hessian matrix is not positive definite. (110) 
    EPS_MUST_BE_POSITVE = 111						# Eps for regularisation must be sufficiently positive. 
    REGSTEPS_MUST_BE_POSITVE = 112					# Maximum number of regularisation steps must be non-negative. 
    HESSIAN_ALREADY_REGULARISED = 113				# Hessian has been already regularised. 
    CANNOT_REGULARISE_IDENTITY = 114				# Identity Hessian matrix cannot be regularised. 
    CANNOT_REGULARISE_SPARSE = 115					# Sparse matrix cannot be regularised as diagonal entry is missing. 
    NO_REGSTEP_NWSR = 116							# No additional regularisation step could be performed due to limits. 
    FEWER_REGSTEPS_NWSR = 117						# Fewer additional regularisation steps have been performed due to limits. 
    CHOLESKY_OF_ZERO_HESSIAN = 118					# Cholesky decomposition of (unregularised) zero Hessian matrix. 
    ZERO_HESSIAN_ASSUMED = 119					# Zero Hessian matrix assumed as null pointer passed without specifying hessianType. 
    CONSTRAINTS_ARE_NOT_SCALED = 120 				# (no longer in use) (120) 
    INITIAL_BOUNDS_STATUS_NYI = 121					# (no longer in use) 
    ERROR_IN_CONSTRAINTPRODUCT= 122				# Error in user-defined constraint product function. 
    FIX_BOUNDS_FOR_LP = 123						# All initial bounds must be fixed when solving an (unregularised) LP. 
    USE_REGULARISATION_FOR_LP = 124				# Set options.enableRegularisation=BT_TRUE for solving LPs. 
    UPDATEMATRICES_FAILED = 125				# Unable to update QP matrices. 
    UPDATEMATRICES_FAILED_AS_QP_NOT_SOLVED = 126	# Unable to update matrices as previous QP is not solved. 
    UNABLE_TO_OPEN_FILE = 127						# Unable to open file. 
    UNABLE_TO_WRITE_FILE = 128						# Unable to write into file.
    UNABLE_TO_READ_FILE = 129						# Unable to read from file. 
    FILEDATA_INCONSISTENT = 130						# File contains inconsistent data. (130) 
    OPTIONS_ADJUSTED = 131					# Options needed to be adjusted for consistency reasons. 
    UNABLE_TO_ANALYSE_QPROBLEM = 132				# Unable to analyse (S)QProblem(B) object. 
    NWSR_SET_TO_ONE = 133							# Maximum number of working set changes was set to 1. 
    UNABLE_TO_READ_BENCHMARK = 134					# Unable to read benchmark data. 
    BENCHMARK_ABORTED = 135						# Benchmark aborted. 
    INITIAL_QP_SOLVED = 136							# Initial QP solved. 
    QP_SOLUTION_STARTED = 137						# Solving QP... 
    BENCHMARK_SUCCESSFUL= 138						# Benchmark terminated successfully. 
    NO_DIAGONAL_AVAILABLE = 139				# Sparse matrix does not have entries on full diagonal. 
    DIAGONAL_NOT_INITIALISED = 140				# Diagonal data of sparse matrix has not been initialised. (140) 
    ENSURELI_DROPPED = 141							# Linear independence resolved by dropping blocking constraint. 
    KKT_MATRIX_SINGULAR = 142					# KKT matrix is singular. 
    QR_FACTORISATION_FAILED = 143					# QR factorization of Schur complement failed. 
    INERTIA_CORRECTION_FAILED = 144					# Inertia correction failed after KKT matrix had too many neg   ative eigenvalues. 
    NO_SPARSE_SOLVER = 145							# No factorization routine for the KKT matrix installed. 
    SIMPLE_STATUS_P1 = 146				# QP problem could not be solved within given number of iterations. 
    SIMPLE_STATUS_P0 = 147						# QP problem solved. 
    SIMPLE_STATUS_M1 = 148						# QP problem could not be solved due to an internal error. 
    SIMPLE_STATUS_M2 = 149						# QP problem is infeasible (and thus could not be solved). 
    SIMPLE_STATUS_M3 = 150						# QP problem is unbounded (and thus could not be solved). (150) 